# Generated by Django 3.2 on 2022-06-04 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(max_length=255)),
                ('machine', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=255)),
                ('ip', models.GenericIPAddressField()),
                ('state', models.CharField(max_length=255)),
                ('cloud_name', models.CharField(max_length=255)),
            ],
        ),
    ]
