# Generated by Django 3.2 on 2022-06-04 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
